### ISSUE TITLE
Problems in make_models.py

### ISSUE THREAD

**Issue by Sargnec** [pytorch/live#32]
### Version

    "react-native-pytorch-core": "0.1.2",

### Problem Area

react-native-pytorch-core (core package)

### Steps to Reproduce

npx torchlive-cli init MyFirstProject

### Expected Results

Create a project without an error

### Code example, screenshot, or link to repository

I get this error when I create new project.
>   › Error project "SmartCalc" is created but we ran into the following issues at generatin…
    ‎ ‎ ‎ ‎
    Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /Users/nec…
    Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.p…
    h.request(req.get_method(), req.selector, req.data, headers,
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py",…
    self._send_request(method, url, body, headers, encode_chunked)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py",…
    self.endheaders(body, encode_chunked=encode_chunked)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py",…
    self._send_output(message_body, encode_chunked=encode_chunked)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py",…
    self.send(msg)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py",…
    self.connect()
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py",…
    self.sock = self._context.wrap_socket(self.sock,
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 50…
    return self.sslsocket_class._create(
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 10…
    self.do_handshake()
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 13…
    self._sslobj.do_handshake()
    ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail…
    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
    File "/Users/necmettinsargin/Documents/GitHub/SmartCalc/models/make_models.py", line 1…
    main()
    File "/Users/necmettinsargin/Documents/GitHub/SmartCalc/models/make_models.py", line 1…
    export_image_classification_models()
    File "/Users/necmettinsargin/Documents/GitHub/SmartCalc/models/make_models.py", line 3…
    "resnet18": torchvision.models.resnet18(pretrained=True),
    File "/Users/necmettinsargin/Documents/GitHub/SmartCalc/models/venv/lib/python3.9/site…
    return _resnet('resnet18', BasicBlock, [2, 2, 2, 2], pretrained, progress,
    File "/Users/necmettinsargin/Documents/GitHub/SmartCalc/models/venv/lib/python3.9/site…
    state_dict = load_state_dict_from_url(model_urls[arch],
    File "/Users/necmettinsargin/Documents/GitHub/SmartCalc/models/venv/lib/python3.9/site…
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
    File "/Users/necmettinsargin/Documents/GitHub/SmartCalc/models/venv/lib/python3.9/site…
    u = urlopen(req)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.p…
    return opener.open(url, data, timeout)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.p…
    response = self._open(req, data)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.p…
    result = self._call_chain(self.handle_open, protocol, protocol +
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.p…
    result = func(*args)
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.p…
    return self.do_open(http.client.HTTPSConnection, req,
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.p…
    raise URLError(err)
    urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate ver…
    ‎ ‎ ‎ ‎
    please rerun
    ‎ ‎ ‎ ‎ • "python make_models.py" in the SmartCalc/models/ directory, and
    ‎ ‎ ‎ ‎ • "pod install" in the SmartCalc/ios/ directory
    if the issue persists, please report at https://github.com/pytorch/live/issues.
  
  And When I run python make_models.py it says
 

>   File "make_models.py", line 17
    print(f"torch version {torch.__version__}")
                                             ^
SyntaxError: invalid syntax

**Comment by aaronespasa** [comment]
Hi @Sargnec ,

The error is due because you didn't install the certificates for Python after installing it locally (its post-installation). You can read more about it in the next link: [urllib and "SSL: CERTIFICATE_VERIFY_FAILED" Error](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error).

I recommend you to install [Python 3.9.5](https://www.python.org/downloads/release/python-395/).

See that, after installing Python, the installer asks you to Install the necessary certificates:
<img width="1069" alt="Screenshot 2022-01-10 at 01 31 04" src="https://user-images.githubusercontent.com/39239895/148707405-00e230e9-c65b-4e21-b019-582a60fc3070.png">


⚠️ Make sure the command `python3` references to this installation of Python 3.9.5. That's because, for the moment, the `python3` command is used to make the models. As a temporal solution, you can add the line `alias python3=<python folder>` substituting `<python folder>` by the path of your local installation of Python like `/usr/local/bin/python3`. You can see this by opening the Python Launcher and copying the path after `Interpreter`.

As soon as I have time to work on it, I'll create a Python Installer on #9 to avoid having this kind of issue.

Thanks for reporting it! 😊

**Comment by Sargnec** [comment]
I did try both 3.9.5 and 3.9.4 and when I click on Install certificate it gives this

> python3.9: posix_spawn: /Library/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0

Btw I'm on macos m1

**Comment by aaronespasa** [comment]
What's the output of the terminal when you write `which python` ?

At first it seems that your Python installation is broken (the default Python 2.7 installation that comes with your Mac).
You can try install Python using [Homebrew](https://brew.sh/): `brew install python`.

Then, make sure `/usr/local/bin` is added to PATH. You can add it manually with the command `export PATH=$PATH:/usr/local/bin`.

After that, try installing the certificates.

And don't worry, it is not an Apple Silicon problem. I'm also using an M1 MacBook.

Hope it works this time @Sargnec ! 😁

**Comment by Sargnec** [comment]
<img width="503" alt="Screen Shot 2022-01-11 at 02 34 57" src="https://user-images.githubusercontent.com/49839699/148855347-0a547505-b422-4929-9c5b-e5b575bfc31a.png">

Do I remove existing python and link python@3.9? @aaronespasa 
And thank you for your help

**Comment by aaronespasa** [comment]
@Sargnec  Do not remove the existing python. Link python@3.9 with the command `brew link --overwrite --dry-run python@3.9` to avoid having the symlink error (`--dry-run` will let you know which files will be removed). You can find more about this issue in StackOverflow: [How to symlink python in Homebrew?](https://stackoverflow.com/questions/13354207/how-to-symlink-python-in-homebrew).

Then, try to install the certificates.

After doing that, keep in mind that Python 3.9.9 will generate some conflict at the time of making the models because it can't find the last version of torchvision. So you will have to downgrade Python to the version 3.9.5 and be sure that the command `python3 -V` outputs the version 3.9.5 of Python. You can follow the steps that I indicated on the first comment to create this alias temporally.

**Comment by liuyinglao** [comment]
Hi @Sargnec 

Thanks for using Pytorch Live!  As @aaronespasa mentioned, this seems to be python version issue and his suggestion seems mostly right! And after you configure the python version correctly on you machine, here are the steps you may want to rerun within your project to re-create the ptl files:

https://github.com/pytorch/live/blob/main/react-native-template-pytorch-live/script.js#L20-L24

Please let us know how does that work for you! Thanks!

**Comment by Sargnec** [comment]
Thank you @aaronespasa @liuyinglao. At first try nothing changed it was giving me same errors 
> > python3.9: posix_spawn: /Library/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python: Undefined error: 0

but today I tried again and I was able to install certificates and right now ImageClassificationTutorial app is working for me.
